### ISSUE TITLE
Travis -> GH Actions

### ISSUE THREAD

**Issue by nikic** [nikic/php-ast#198]
It would be nice to migrate from Travis to GH actions.

**Comment by nikic** [comment]
Sorry, don't have any examples myself -- I was hoping you did ^^

**Comment by TysonAndre** [comment]
I started looking at github actions for another project.

Once I figured it out, it looked remarkably straightforward, e.g. ubuntu has docker pre-installed, and sudo in a docker worked properly (unlike azure pipelines)

So once one writes a script to docker build and/or docker run that can be reused in github workflows. I imagine `FROM php:$PHP_VERSION` could be used with a dockerfile template (e.g. use sed to replace PHP_VERSION before running docker)

`.github/workflows/main.yml`


```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
    strategy:
      matrix:
       include:
         - PHP_VERSION: 7.0
         - PHP_VERSION: 8.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build and test in docker
        run: bash ./test_in_docker.sh ${{ matrix.PHP_VERSION }}
```
